image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - lint

lint:
  stage: lint
  script:
    - npm install
    - npm run lint
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
