image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - npm install
    - npm run lint
  allow_failure: true
  cache:
    key: '$CI_COMMIT_REF_NAME'
    policy: pull
    paths:
      - build

test:
  stage: test
  dependencies:
    - lint
  script:
    - npm run test
